settings:
  title: 'Read This Paper 狀態 / Status'
  url: 'https://status.readthispaper.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '正常運作 - All Systems Operational'
  notAllmonitorsOperational: '部分正常運作 - Partial Systems Operational'
  monitorLabelOperational: '運作中 - Operational'
  monitorLabelNotOperational: '異常 - Not Operational'
  monitorLabelNoData: '無資料 - No data'
  dayInHistogramNoData: '無資料 - No data'
  dayInHistogramOperational: '全部正常 - All good'
  dayInHistogramNotOperational: ' 事件/incident(s)' # xx incident(s) recorded

monitors:
  - id: index-page # unique identifier
    name: Read This Paper 網頁 - Frontend
    description: 'Read This Paper Website' # default=empty
    url: 'http://www.readthispaper.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ss-search-api # unique identifier
    name: Searching API - 搜尋 API (Semantic Scholar)
    description: 'Read This Paper Searching API Status' # default=empty
    url: 'http://api.readthispaper.com/ss-srv/v1/query_page?query=bert&page_size=10&current_page=1' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ss-reading-insight-api
    name: Reading Insight API - 閱讀順序演算法 API (Read This Paper - Reading Order)
    description: 'Read This Paper Reading Insight API Status'
    url: 'https://api.readthispaper.com/ss-srv/v1/reading_insight/db1170606650201b5d4f262bdd96d517628a9c59'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: ss-key-concept-api
    name: Key Insight API - 關鍵概念演算法 API (Read This Paper - Key Concept)
    description: 'Read This Paper Key Insight API Status'
    url: 'https://api.readthispaper.com/ss-srv/v1/key_insight/db1170606650201b5d4f262bdd96d517628a9c59'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: ss-pwc-api
    name: Paper with Code API (Paper with Code)
    description: 'Read This Paper Paper with Code API Status'
    url: 'https://api.readthispaper.com/cf/papers_with_code/?query=ALBERT:%20A%20Lite%20BERT%20for%20Self-supervised%20Learning%20of%20Language%20Representations'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: skyup-gateway
    name: SkyUp Gateway Test
    description: 'Read This Paper Paper with Code API Status'
    url: 'https://api-gateway-01.skyup.in/question-lake/api/v1/test/session'
    method: GET
    expectStatus: 401
    linkable: false # allows the title to be a link, default=true
